### ISSUE TITLE
Question on ImportanceWeightedSampler

### ISSUE THREAD

**Issue by LeoLiu1998** [wohlert/semi-supervised-pytorch#13]
I notice that in [this line](https://github.com/wohlert/semi-supervised-pytorch/blob/7cde4959468d271552febdcfed5e1cfae9857613/semi-supervised/inference/variational.py#L25) the resampling is simply repeat the given x, is there any particular reseaon to do this? I am just feeling it doesn't fit my understanding of sampling, where you kep drawing from some distribution. It also looks different from [Casper's code](https://github.com/casperkaae/LVAE/blob/066858a3fb53bb1c529a6f12ae5afb0955722845/run_models.py#L97). I wish I can have a brief discussion with you about this.

**Comment by wohlert** [comment]
It has the same functionality, as it introduces the same randomness downstream in the model.

If you have a random variable x(y) that depends on y you can either send in a single y, fix it and sample n times. What I do instead is to make n copies of y, send them through x and then sample once.

Both operations are mathematically equivalent, but Casper's method is more computationally efficient due to the fact that we don't need to send copies through the inference network.

The reason why I choose this option was because parts of the code was originally ported from an internal TF project by [Lars Maaløe](https://github.com/larsmaaloee) in which multiple sampling was not available at the time.

**Comment by LeoLiu1998** [comment]
But if you just `repeat` and then average, wouldn't that be the same as original input, or are you suggesting both approaches will be "random" and won't matter which one we use?

**Comment by wohlert** [comment]
Consider my approach:
```
x = torch.randn(64, 784) # mock data
x = x.repeat(10, 1) # size => [640, 784]
h_mu, h_log_sigma = encoder(x)
epsilon = torch.randn(h_mu.size()) # size => [640, 32]
z = h_mu + h_log_sigma * epsilon
x_hat = decoder(z) # size => [640, 784]
x_hat = x_hat.view(64, 10, 784)
```

and the other approach:
```
x = torch.randn(64, 784) # mock data
h_mu, h_log_sigma = encoder(x)
epsilon = torch.randn(64, 10, 32)
z = h_mu + h_log_sigma * epsilon  # size => [64, 10, 32]
x_hat = decoder(z) # size => [64, 10, 784]
```

The randomness is introduced in epsilon, so the behaviour is the same.

**Comment by LeoLiu1998** [comment]
I see, thank you so much!
