### ISSUE TITLE
which is the state of the art since 2017?

### ISSUE THREAD

**Issue by bhomass** [wohlert/semi-supervised-pytorch#26]
You mentioned auxiliary variable VAE was the SOTA until 2017. Who replaced it since then?

**Comment by wohlert** [comment]
I think at the time, the following was outperforming ADGM.

- T. Salimans, I. Goodfellow, W. Zaremba, V. Cheung, A. Radford, and X. Chen. [Improved techniques for training GANs](https://arxiv.org/abs/1606.03498)

The ADGM author later improved the results for fewer label.

- L. Maaløe, M. Fraccaro, O. Winther. [CaGeM: A Cluster Aware Deep Generative Model](https://marcofraccaro.github.io/download/publications/cagem.pdf)

I haven't followed the development since, but I assume that there are better methods now.

**Comment by bhomass** [comment]
possibily this one

https://arxiv.org/pdf/1905.02361.pdf
