### ISSUE TITLE
Add Support for Tensorflow for Better Flexibility

### ISSUE THREAD

**Issue by akashmishra23** [wohlert/semi-supervised-pytorch#6]
It'll be Awesome if We could transition this project to tensorflow for improved flexibility, I'm working on it as we speak but having a helping hand would make things easier

**Comment by wohlert** [comment]
That is a definite no for this project, as I personally feel that Tensorflow is the weaker framework on the market at the moment. This project was initially started in Tensorflow, but because of the static graph execution, we ran into too many problems with conditional inputs. It can be done, but it is very cumbersome.

You can check out the original implementation of [ADGM in Theano](https://github.com/larsmaaloee/auxiliary-deep-generative-models/blob/master/models/sdgmssl.py) to get the idea.

I have also experimented with Tensorflow Eager, but at the moment it is several times slower than PyTorch to be used in any meaningful way.

 If you want to create your own version in Tensorflow that is totally fine, but I do not have enough knowledge to help you.

**Comment by akashmishra23** [comment]
@wohlert If that's the case, Then Instead of going through all that work, I can simply rewrite my projects in PyTorch as they have improved the support for windows since I started working on this.
